### ISSUE TITLE
When block color is changed to have background color, text is indented

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-2022#126]
On text in a block when I change the block color to background and select a color, the text gets indented. If I toggle the selected block color background the text is no longer indented.

When block color background color is selected (text is indented):
![Background text indented](https://user-images.githubusercontent.com/9750983/187958493-937e38c3-fa11-476a-89bd-70b00b36add0.jpg)

![Block color_background_color_selected indents text](https://user-images.githubusercontent.com/9750983/187960280-044c2f15-ee2b-426a-a65c-3a0b51580512.jpg)

If the text in a block has no block color set to background (no color is checked), the text is not indented (desired behavior). 
![Text not indented when no background color selected](https://user-images.githubusercontent.com/9750983/187960995-cfaac9a4-bb78-427c-911f-526654ad1689.jpg)

**Comment by knice** [comment]
This is a feature built into the WordPress editor. It prevents text in boxes from looking strange when the box has a background color. We can't alter this feature.

**Comment by CorinneOC** [comment]
Thanks Rob. For context if one wanted to have nested Campus Directory blocks (as in the way University Relations page appears in WCMS) the background color text for the sub group would be indented and the Campus Directory block would be outdented from the sub group text
