### ISSUE TITLE
Finalize accordion block styles  

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#128]
We need to better distinguish between `summary` and the rest of the content in the `details` element.

- [ ] Some indentation in the content that comes after `summary`
- [ ] Typographic distinction between `summary` and the rest of the content

**Comment by teresasilva71** [comment]
@Herm71 @knice In our open lab today, this was brought up as a request again. Asking for status of this.

**Comment by knice** [comment]
Styles for the accordion block will go live with the 12/14 release of the theme.
