### ISSUE TITLE
Double Search icons on Mobile

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#132]
![IMG_1509](https://user-images.githubusercontent.com/7795841/189238473-b8b09326-0b16-4aa6-a571-ecb94f42033b.jpg)

**Comment by Herm71** [comment]
I believe I've fixed this.

![ucsc-mobile-search](https://user-images.githubusercontent.com/1000543/189766183-7f68bf05-acc9-4745-9d16-08ebfdba8f2a.png)

**Comment by knice** [comment]
After some investigation, we discovered that the icon and gray box are styles added by Safari on iOS. [We found a solution](https://stackoverflow.com/a/5819374/1258502) and @Herm71 will implement it.
