### ISSUE TITLE
RSS Feed text size

### ISSUE THREAD

**Issue by luckyluke007** [ucsc/ucsc-2022#135]
Unable to change the text size for the News feed RSS.

<img width="1170" alt="Screen Shot 2022-09-13 at 9 10 21 AM" src="https://user-images.githubusercontent.com/1154568/189952969-71e47acc-a8f9-4147-97ad-af5a6ac3dce5.png">

**Comment by knice** [comment]
Maybe a _block style_ for different heading levels.
