### ISSUE TITLE
Site Title getting accessibility warning

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#138]
![website title](https://user-images.githubusercontent.com/7795841/190454481-42c0265c-1396-496a-87d5-dad58070d787.jpg)
Looks like the Heading tag isn't getting recognized. 
Using the Wave Chrome plugin.

**Comment by knice** [comment]
@teresasilva71 This is an internal page, correct? If so, that's not supposed to be a headline tag. It's a paragraph intentionally because the page title is the h1--which is a best practice. We might have outsmarted the plugin.
