### ISSUE TITLE
Change width of tile layout

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#148]
Becca in INC1347815 asks:

Is it possible to eventually change the width of the tile layout of the campus directory block if it is just one profile being represented in the column?  Why:  So the text for the office will not break into two lines: 

See an example of what is happening here:
https://engineering.wordpress.ucsc.edu/departments/applied-mathematics/people/

The mobile view shows the table having more width.

**Comment by teresasilva71** [comment]
Bryn, what if she did a two column layout and selected the list layout for the block? Does that fix the problem?

**Comment by kanarb** [comment]
Good idea Teresa. I've added that suggestion to the ticket.

**Comment by knice** [comment]
I'm going to close this ticket since this is an issue with the directory block. If there is anything we need to do for this problem, re-open the issue.
