### ISSUE TITLE
Breadcrumbs too tiny

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/ucsc-2022#150]
While in the Thursday, October 20, 2022 WordPress Open Lab Jennie Kulczyk commented that the breadcrumbs are too tiny.
Adam agreed and said that the Web Team will investigate.
![Screen Shot 2022-10-20 at 10 07 19 AM](https://user-images.githubusercontent.com/1775933/197014356-aa43c9e2-8f13-4598-b758-e6a03abf7a7d.png)

**Comment by knice** [comment]
This is resolved
