### ISSUE TITLE
Feature Request: Hover link change in menu block

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#159]
From Jennie K.
"In last week's open lab it was mentioned I could get help with building a menu block or pattern for OR. I'm getting closer to what's been asked for with a reusable block I'm calling "ORBO separator menu" which you can see in action on [](https://officeofresearch.wordpress.ucsc.edu/orbo/about-us/)

The part of the request that I don't know how to do is to make the items in the menu not formatted as links, despite them linking to other pages on our site. The example I was shown of another campus site which is on WordPress and does this: [](https://transform.ucsc.edu/work/campus-community/)

Ideally, we'd also want the highlighting that happens on the example menu when a cursor hovers over an option, but I believe you said in the lab that's not something we can do now."

**Comment by knice** [comment]
Resolved with a combination of updates to WordPress core and styles added to the list block
