### ISSUE TITLE
Link Color Problem

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#164]
Sean Tran in INC1407222 reports a problem with the color of a link. From the screenshot he attached, it looks like the link is black text on a blue background and needs to be white or a light color.
<img width="1792" alt="Screen Shot 2022-12-01 at 4 48 38 PM" src="https://user-images.githubusercontent.com/5742093/205345961-3b5bf713-16bd-4d4b-9c83-088c55998077.png">

**Comment by kanarb** [comment]
Here is the info Sean provides in the ticket:

I am trying to modify the text color of a link to match the surrounding text, but it doesn't seem to be changing the link's color. See attached screenshot, it would be great if the link can be changed to be the same color as the text above.

**Comment by knice** [comment]
We're aware of this issue. @Herm71 actually [fixed it in the codebase yesterday](https://github.com/ucsc/ucsc-2022/commit/bfb38a233a5f1ef285178570b29fcaba930789aa). Users will be able to modify link colors in the next release of the theme, which goes to production Wednesday of next week.

**Comment by kanarb** [comment]
Thanks Rob. I resolved the ticket.
