### ISSUE TITLE
Question about the space between the top blue bar and the page title

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#166]
Becca (in INC1408438) asks about the spacing at the top of the page:

There is a lot of space between the title and the top blue bar? Is that so we can add a logo?

![Screen Shot 2022-12-02 at 9 48 16 AM](https://user-images.githubusercontent.com/5742093/205692761-bb9f18d4-4efb-43e3-aec8-72bc3098edb6.png)

**Comment by knice** [comment]
Tomorrow's release will reduce that space and refinements continue. But there will be space there as part of the design.

**Comment by knice** [comment]
Next week's release will shrink the space a bit more. I'll close this issue after the 12/14 release is in production.

**Comment by knice** [comment]
This is also documented in #100. We are working on this as part of refinements to the entire global header.

**Comment by knice** [comment]
This is resolved.
