### ISSUE TITLE
Site Title, Page Title, and Page H2 need to be more distinct

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#167]
### Description

Becca (in INC1408438) asks:

May we please have more differences between the Site Title 
H1
H2
On the Desktop browser, they appear to be all the same size.

### Step-by-step reproduction instructions

Go to: https://becomputing.wordpress.ucsc.edu/

### Screenshots, screen recording, code snippet

![Screen Shot 2022-12-02 at 9 48 16 AM](https://user-images.githubusercontent.com/5742093/205694018-94282b98-5048-4a73-95f2-7ab548ce9450.png)

### Environment info

https://becomputing.wordpress.ucsc.edu/

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by kanarb** [comment]
I added your question to the ticket and will let you know when Becca replies.

**Comment by kanarb** [comment]
Hey Rob. Here is Becca's answer to your question about all caps in the page title:

I made the Site Title in all caps to mimic what I was seeing other places, the all caps isn't set in stone just trying to move this project along

**Comment by knice** [comment]
This is resolved with more recent versions of the theme.
