### ISSUE TITLE
Issue with the header on mobile.

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#169]
### Description

Becca (in INC1412682) reports the following issue with the header on mobile:

Working with the campus theme for the Baskin Computing Support Site I noticed that  menu  is very squshed and the magnifying class is over the search area

### Step-by-step reproduction instructions

1. Go to https://becomputing.wordpress.ucsc.edu/ on a mobile device
2. Look at the header, particularly the search area

### Screenshots, screen recording, code snippet

![IMG_7077](https://user-images.githubusercontent.com/5742093/206518450-3cbdd30e-74d2-4fbf-9a9f-d6211754d7ac.PNG)

### Environment info

https://becomputing.wordpress.ucsc.edu/

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
This is also documented in #100. We are working on this as part of refinements to the entire global header.

**Comment by knice** [comment]
This is resolved in v2.0.0 of the theme, which removed the global header and global footer from the theme.
