### ISSUE TITLE
Accordion styling | yellow line issue

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#174]
### Description

The change to the accordion styling has created a yellow line that extends past the boundaries of the block on https://officeofresearch.wordpress.ucsc.edu/about/contact-us/ - when the sections are expanded, the yellow line crosses over into the menu block.

### Step-by-step reproduction instructions

1. Create an accordion block
2. Look at yellow line

### Screenshots, screen recording, code snippet

<img width="489" alt="Screen Shot 2022-12-16 at 10 03 43 AM" src="https://user-images.githubusercontent.com/5742093/208160941-7104f329-9846-47ab-a94e-0645f806d9b0.png">

### Environment info

https://officeofresearch.wordpress.ucsc.edu/about/contact-us/

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by kanarb** [comment]
Hi @knice @Herm71 any update on this? Thanks.

**Comment by knice** [comment]
I will handle this.

**Comment by knice** [comment]
Fix will be deployed to CampusPress next week.

**Comment by knice** [comment]
Deployed
