### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#175]
### Description

Becca (in INC1420664) reports that the link to 'Accessibility' in the footer is a broken link.

### Step-by-step reproduction instructions

Go to any page that uses the UCSC 2022 theme and click on the Accessibility link in the footer.

### Screenshots, screen recording, code snippet

<a href="#">Accessibility</a>

### Environment info

Any site that uses the UCSC 2022 theme.

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by kanarb** [comment]
@knice @Herm71 Just checking to see if this issue is on your radar.

**Comment by knice** [comment]
The fix for this will go live on CampusPress next week.

**Comment by knice** [comment]
Fixed
