### ISSUE TITLE
Image captions have a gradient

### ISSUE THREAD

**Issue by Herm71** [ucsc/ucsc-2022#180]
### Description

Image captions default styling adds a gradient. It's kinda ugly.

### Step-by-step reproduction instructions

Add image to a page. Add a caption.

### Screenshots, screen recording, code snippet

![image-captions](https://user-images.githubusercontent.com/1000543/214901849-7d8f31b1-59af-43ae-af19-1a4c1cb8399e.png)

### Environment info

This is part of the UCSC Theme, so any site with a caption.

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
This appears to be fixed.

![screenshot-2023-10-04-074143](https://github.com/ucsc/ucsc-2022/assets/36719/6e2f1639-18cb-4b39-826c-f23d272dbb6b)
