### ISSUE TITLE
Change site header to blue background with white text

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#185]
Discussed in the C&M design patterns meeting on 2023-02-13

- Tighten up empty space a bit
- Gold border at the bottom 

![screenshot-2023-02-13-152034-2](https://user-images.githubusercontent.com/36719/218890880-be4500db-ea69-4766-9dd6-74f7dbef2239.jpg)

**Comment by teresasilva71** [comment]
HI Rob, is this a change for all sites or just www?

**Comment by knice** [comment]
@teresasilva71 Once implemented, this would be on all sites.

**Comment by teresasilva71** [comment]
Ok, when would you like to propose this go into prod?

**Comment by knice** [comment]
I haven't done the work yet. When I've completed the work, it would be part of a normal theme release, with a couple of week's notice of course.

**Comment by teresasilva71** [comment]
Oh gotcha!
