### ISSUE TITLE
Create an “intro” paragraph style

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#188]
- Slightly larger font-size, and probably a different color
- Intended for use as TLDR text following the page title, before the page content begins 

![screenshot-2023-02-13-152034-2](https://user-images.githubusercontent.com/36719/218891475-0c70edf6-866b-4b65-83c1-ce6c588cf883.jpg)

**Comment by teresasilva71** [comment]
Hi Ro, is this a block type? Or is this just a styling to a heading block?

**Comment by knice** [comment]
@teresasilva71 This will be a style option on the paragraph block. There will be a button in the block options panel, similar to how button block styles are chosen.
