### ISSUE TITLE
Broken Email Link in Campus Directory Block

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/ucsc-2022#259]
### Description

Reported in INC1653116 - Broken links created with Campus Directory Block
At a person's directory page when you select an email address a 404 error page is returned.
It should open an email with the person's email.
The "mailto:" is missing.

### Step-by-step reproduction instructions

Select either email link at https://be-toolkit.wordpress.ucsc.edu/faculty/etc/?directoryprofilecruzid=jquynn and a 404 page is returned.

### Screenshots, screen recording, code snippet

![Screenshot 2023-08-18 at 9 19 53 AM](https://github.com/ucsc/ucsc-2022/assets/1775933/6fd214d9-a8d7-4c64-9e7c-6bb3f1662895)

### Environment info

https://be-toolkit.wordpress.ucsc.edu/faculty/etc/?directoryprofilecruzid=jquynn

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
@thomasgardner This will need to go to Kumar on [this Github project repo](https://github.com/ucsc/ucsc-gutenberg-blocks).
