### ISSUE TITLE
Double underline appearing on linked text

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/ucsc-2022#260]
### Description

Reported in INC1649562 - Double underline appearing on linked text

- https://be-toolkit.wordpress.ucsc.edu/communications/
- https://be-toolkit.wordpress.ucsc.edu/website-support/
- https://be-toolkit.wordpress.ucsc.edu/event-support/

### Screenshots, screen recording, code snippet

![Screenshot 2023-08-18 at 5 27 08 PM](https://github.com/ucsc/ucsc-2022/assets/1775933/c52d41f0-becd-44b6-b2d7-dffed869b0ba)

### Environment info

- https://be-toolkit.wordpress.ucsc.edu/communications/
- https://be-toolkit.wordpress.ucsc.edu/website-support/
- https://be-toolkit.wordpress.ucsc.edu/event-support/

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
Pattern has underlined headers by default. That means **linked** items have a second underline. The second one shows because we have different `text-decoration-offset` numbers.

**Comment by knice** [comment]
I believe this issue is resolved. If I am incorrect, you can re-open it
