### ISSUE TITLE
Page title too close to nav bar

### ISSUE THREAD

**Issue by thomasgardner** [ucsc/ucsc-2022#261]
### Description

Reported in INC1649564:

Hello, we've noticed the page titles are appearing too close to the nav bar on our Baskin Engineering toolkit website: https://be-toolkit.wordpress.ucsc.edu/

Here are some webpages as examples you can see this happening:
https://be-toolkit.wordpress.ucsc.edu/communications/
https://be-toolkit.wordpress.ucsc.edu/etc/

Are you able to adjust so there is more spacing between the page title and the nav bar?

### Screenshots, screen recording, code snippet

![Screenshot 2023-08-18 at 5 34 32 PM](https://github.com/ucsc/ucsc-2022/assets/1775933/6bee2d56-5754-49cd-ab2e-414005bfe49e)

### Environment info

- https://be-toolkit.wordpress.ucsc.edu/communications/
- https://be-toolkit.wordpress.ucsc.edu/website-support/
- https://be-toolkit.wordpress.ucsc.edu/event-support/

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
This was resolved in v3.2.0
