### ISSUE TITLE
Incorrect favicon on WCMS sites

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-2022#269]
### Description

WCMS sites are showing the default wordpress favicon instead of the UCSC favicon.

### Step-by-step reproduction instructions

1. Go to a wcms site, such as history.ucsc.edu
2. View the favicon in the browser tab

### Screenshots, screen recording, code snippet

<img width="161" alt="Screen Shot 2023-09-20 at 3 30 59 PM" src="https://github.com/ucsc/ucsc-2022/assets/5742093/7e1f7f65-a6c6-4254-a252-f1b1e8fc7ac5">

### Environment info

 - https://history.ucsc.edu/
 - Chrome Version 116.0.5845.187 (Official Build) (x86_64)
 - MacOS Catalina (10.15.6)

### Please confirm that you have searched existing issues in the repo.

Yes

**Comment by knice** [comment]
I've fixed the favicon in WordPress. The URL WCMS sites use is https://www.ucsc.edu/favicon.ico now redirects to the proper UCSC favicon. Browsers tend to cache favicons, so I'm not sure how fast individual users' browsers will change. But this issue is resolved.
