### ISSUE TITLE
Zoom effect on hover when an image is linked

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#340]
- [x] **When linked**, a Featured image inside the **UCSC Query Loop Card** pattern will enlarge inside of its bounding box in hover, focus, and active states
- [x] An unlinked Featured image will not do this
- [ ] A block style for the ~~image~~ ~~Featured Image block~~ Pattern(?) will toggle this behavior
- [x] Check for other blocks that may use images within their content
- [x] This feature will check for "prefers reduced motion" preferences via a media query

**Comment by Herm71** [comment]
I did some research on this and made a slight edit above ⬆️ .  The **Featured Image** block behaves this way when it's _inside_ a **Post Template** block _inside_ a **Query Loop** block. 

A **Featured Image** block placed on  a page/post _by itself_ outside a loop and template with "Link to Page" toggled will not "zoom."

There is also a **Co-Author Featured Image** block that has a toggle to link to the Author's archive page. I have not yet determined whether it hovers when this option is toggled.

**Comment by Herm71** [comment]
The commit above ⬆️ adds the `prefers-reduced-motion` media query to the `<img>` element in  the [`block-patterns/_cards.scss`](https://github.com/ucsc/ucsc-2022/blob/8857b6e7cf79286c344881fc36bed1c3335ad044/src/scss/block-patterns/_cards.scss#L25) file

```css
img {
	transform: scale(1.15);

	@media screen and (prefers-reduced-motion: reduce) {
	  transform: none;
	}
}
```

### Demo:
(note: demo uses Firefox. Firefox and Safari automatically detect the `reduce` flag, whereas Chrome requires a deeper dive into its settings.)

https://github.com/ucsc/ucsc-2022/assets/1000543/fa4be53b-00d5-4cec-8c89-4be8afece683

**Comment by knice** [comment]
This should apply to **any linked image**. And we won't add block styles to remove it.
