### ISSUE TITLE
Error message in header area 

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#39]
There is an error message when I go to edit my menu on my site.
"Your site doesn't include support for the "outermost/icon-block" block. You can leave this block intact, ...."
![theme header](https://user-images.githubusercontent.com/7795841/166960224-d4ce8fb3-0310-4b77-bea9-f015c38eb82f.jpg)
I'm not sure what I should do with it?
Will users see that message when they go to create / edit their menus on their sites?

**Comment by knice** [comment]
@teresasilva71 **The Icon Block** plugin is now available on all CP sites. It will be activated on all **new** sites created after today. But it needs to be activated manually on _existing_ sites. Activate the plugin and the error will go away. I've already activated the plugin on websites.wordpress.ucsc.edu.
