### ISSUE TITLE
Icon for "links to different website"?

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#42]
Do you have thoughts/plans for an icon that appears when a nav link takes you away from a website? Something like (attached) image.
![link out icon](https://user-images.githubusercontent.com/7795841/167198227-18ffc890-c016-4da0-b057-8cc96d0854d5.jpg)

**Comment by knice** [comment]
Can you provide some kind of recommended guidance for when this icon should appear? Should it appear for a link that goes from one UCSC site to another UCSC site? Or should it only appear when a link goes off the UCSC domain entirely?

**Comment by Herm71** [comment]
I looked at that Gartner page. Those little arrows appear to be for decoration only; clicking on them just takes you to their respective page within the same site in the same browser tab i.e., _not_ to another domain in a new tab. WordPress uses a similar icon in the Page/Post editor for the "Preview" link, which _does_ open in a new tab. Moreover, we'd have no idea how to track these links. How would we know if, say, Humanities linked over to Arts on one of their posts or pages?

![wp-dash](https://user-images.githubusercontent.com/1000543/169528609-29ab974b-e29a-4138-8a41-c3d3d59f0686.png)

**Comment by knice** [comment]
I'm going to close this issue. While it's possible to add indicator icons to external links, it is imprecise in CSS and usually requires additional javascript. I don't want to add javascript dependencies for a such a minor feature.
