### ISSUE TITLE
Header sizes need more differentiation

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#44]
This page that Adam created uses both H2 and H3 headers. The size looks to be the same?

![header size](https://user-images.githubusercontent.com/7795841/167484110-5e9b1cd2-5442-43d1-b38a-fb0a62f04c78.jpg)

**Comment by knice** [comment]
This will be fixed in the next theme release

**Comment by knice** [comment]
This is resolved in [1.0.0-rc.3 of the theme](https://github.com/WordPress/gutenberg/issues/27614), which will be live on CP on 2022-05-11.
