### ISSUE TITLE
Add UCSC favicon to theme

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#50]
Do we want the UCSC one on the WP network?

**Comment by knice** [comment]
Jason will add favicon to theme so it can't be altered at the site level. [ucsc-website-icons.zip](https://github.com/ucsc/ucsc-2022/files/8703519/ucsc-website-icons.zip)

**Comment by knice** [comment]
![logo](https://user-images.githubusercontent.com/36719/168855855-718300ba-e3bd-48ec-924d-bfafc1ff9b63.svg)
