### ISSUE TITLE
Feedback form setup

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#51]
Specifications for consistent web feedback form behavior on all sites:

1. Have a feedback form setup at ___.ucsc.edu/feedback.
2. When submitted, site managers (the UCSC site admin role) are always notified.
3. We configure a basic form to a campus standard.

Next steps:

1. Setup and test locally
2. Approval from WordPress theme team
3. Setup a form at the correct URL on the `site template` site in CampusPress

**Comment by knice** [comment]
Available plugins: https://docs.google.com/spreadsheets/d/1zIEF1kraU2WHVgXpTr9zFR7KM3OX3KjssN2XFJTMbqs/edit#gid=0

**Comment by Herm71** [comment]
[Basic implementation](https://test-jchafin.wordpress-dev.ucsc.edu/1847-2/) of formidable Feeback form, fields adapted from ucsc.edu/feedback. Form sends a copy as email notification to the Site Manager (or any additional role we assign) and saves a copy in the dashboard. 

Formidable includes layout classes that can be used to design custom layouts (CSS Grid). I have applied a few to create rows.

I believe this link satisfies the first three items on the list, notwithstanding any design adjustments that need to be made.
