### ISSUE TITLE
Add content rendering to PHP template

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#53]
Document the process for a plugin to overwrite the `post_content` variable so plugin content is properly wrapped with structural HTML from the theme. 

Reference:
1. https://wordpress.stackexchange.com/questions/225625/where-to-hook-into-post-content

**Comment by Herm71** [comment]
The process has bee documented in the [wiki](https://github.com/ucsc/ucsc-2022/wiki/Theming-content-from-within-a-plugin).
Additionally a Starter Plugin is available in a repo and can be forked [here](https://github.com/ucsc/ucsc-content-starter-plugin).

**Comment by knice** [comment]
All done 🥳
