### ISSUE TITLE
Creating Menus

### ISSUE THREAD

**Issue by kathyduarte** [ucsc/ucsc-2022#54]
Creating a menu causes this error. It's not allowing me to edit /create a new menu. I tried editing the menu of an already established site and got the same error.  

<img width="1636" alt="Screen Shot 2022-06-23 at 3 16 53 PM" src="https://user-images.githubusercontent.com/62771705/175424468-12754f1b-e82b-4d37-a57e-307d192d012a.png">

**Comment by knice** [comment]
This was an error with WordPress 5.8 and a recent version of the Gutenberg plugin. We upgraded to WordPress 6 in early-July. That resolved this issue.
