### ISSUE TITLE
Course Schedule Block Empty Feed

### ISSUE THREAD

**Issue by Yingkit22** [ucsc/ucsc-2022#55]
Hello, classes are not showing up on the Course Schedule block.
<img width="1362" alt="Screen Shot 2022-06-24 at 3 28 40 PM" src="https://user-images.githubusercontent.com/103080126/175714055-51ad658e-fedc-4e5e-a4d4-91b1b953e5a5.png">

**Comment by teresasilva71** [comment]
HI Yingit. I checked and you had the code in lower case "lgst"
I changed it to all caps and now it's showing.
All course/class codes are case sensitive.
Closing
