### ISSUE TITLE
Spacing + Padding 

### ISSUE THREAD

**Issue by kathyduarte** [ucsc/ucsc-2022#58]
There seems to be close to little padding on the bottom of any page. Teresa suggested I open a ticket since I was manually adding in an extra space at the bottom of the pages to recreate the padding. 

This is the padding of a wcms site:
<img width="1450" alt="Screen Shot 2022-07-12 at 1 56 13 PM" src="https://user-images.githubusercontent.com/62771705/178593940-f5741cce-85db-44f8-8a39-6e3b9d1a5dd8.png">

This is the padding of a wodpress site: 
<img width="1513" alt="Screen Shot 2022-07-12 at 1 57 09 PM" src="https://user-images.githubusercontent.com/62771705/178593989-0630e7ba-7811-4f0a-841b-a4ecba7130c6.png">

**Comment by knice** [comment]
Thank you for reporting this, @kathyduarte. With the recent footer redesign, I added spacing between the end of the content area and the beginning of the page footer.

![screenshot-2022-07-20-163151](https://user-images.githubusercontent.com/36719/180100029-0b31ef92-665c-48b1-b2f2-7b879f9f2bc8.jpg)
