### ISSUE TITLE
Block Error

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#59]
![block recovery](https://user-images.githubusercontent.com/7795841/179085569-ddde0e7e-5418-4c0f-8199-c7ca9e258355.jpg)
I'm getting this error when editing existing pages. When I click on the error, it resolves. Weird.

**Comment by knice** [comment]
This happens **any** time a block isn't working correctly. It could be any block. Without knowing which block is causing the issue, I don't know if it's a problem with WordPress or the theme. If you see an issue like this consistently, create a new issue and let us know which block is causing the error.
