### ISSUE TITLE
Nav Link issues

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#60]
For some reason, some links are bolded, and some aren't. Not sure if it's "visited link" behavior that's not going away?
Can you make the links the dark blue?
![bold links](https://user-images.githubusercontent.com/7795841/179087067-6ac68fb8-1015-42f7-b499-741fe5919fd6.jpg)
?

**Comment by knice** [comment]
The current page link, or current menu item if the current page is linked in a dropdown is bold.

It looks like a bug in WordPress. For some reason the services link has the `current_menu_item` class when you are on the Getting started page.

**Comment by knice** [comment]
I believe the bug where two items were marked "current" is now fixed (in WordPress core). The bold text for current links is a theme feature. We can review and change that as part of our regular theming work. Closing this ticket since the first issue is fixed.
