### ISSUE TITLE
Block Alignment issues - 2 column and/or media text blocks

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#61]
![column alignment](https://user-images.githubusercontent.com/7795841/179092834-4acbebbd-1d6b-4ea6-b661-5c3a7bd3d5b9.jpg)
Text should be aligned to the left (page title)

**Comment by knice** [comment]
Removing the background color from the `columns` block and the `column` will resolve this. Columns **automatically** get padding when a background color is selected.

Example: https://share.cleanshot.com/yMvnvWyTqfXqfLOuVcKl/download
