### ISSUE TITLE
Composer artifacts built with Github Actions are causing issues on CampusPress

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#71]
CampusPress rejected the last theme build. They cited this issue. In [`/vendor/composer/autoload_real.php`](/ucsc/ucsc-2022/vendor/composer/autoload_real.php), line 32:

` \Composer\Autoload\ComposerStaticInit32b55e969bfaef7662cb8ee961e47e83::getInitializer($loader)();`

Same line, in the build by Github Actions:

`call_user_func(\Composer\Autoload\ComposerStaticInite5dbd89443cd5604e2dea5f14dca0871::getInitializer($loader));`

**Comment by knice** [comment]
First attempt to fix this is to see if we can opt out of Composer for loading the Breadcrumb PHP class. If we can load the class directly without too much trouble, we'll remove the composer autoloader and use the Breadcrumb class directly.

If we cannot fix it that way, we will yank it for now and come back to it.

**Comment by knice** [comment]
[Documentation on optimizing Composer autoload files](https://getcomposer.org/doc/articles/autoloader-optimization.md).

We aren't able to use any of these strategies because Hybrid Breadcrumbs:

`Class Hybrid\Breadcrumbs\Query\WeekArchive located in ./vendor/justintadlock/hybrid-breadcrumbs/src/Query/Week.php does not comply with psr-4 autoloading standard.`

**Comment by knice** [comment]
CampusPress indicates that the issue may be with their deployment script. I'm going to wait to take any further action on this issue until CampusPress provides more detail.

![screenshot-2022-07-26-170601](https://user-images.githubusercontent.com/36719/181132997-ba7d6085-accf-4b80-bef5-5d4762242c5c.jpg)

**Comment by knice** [comment]
We need to confirm this works on CampusPress before we close the issue.

**Comment by Herm71** [comment]
D'oh. My bad.

**Comment by knice** [comment]
This is fixed. 💯
