### ISSUE TITLE
Forms: change to black text color

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-2022#81]
### Background
Formidable Forms appears to use Bootstrap to style its forms. That means it uses a different font and different form input styles than our theme. There are settings in the FF dashboard for different style settings.  

Investigate the best way to have formidable forms use _theme_ styles instead of its own styles. Ideally we want to turn off FF styles altogether, but that may not be possible with conditional forms and other advanced kinds of forms.

**Comment by Herm71** [comment]
![formidable-dash-no-style](https://user-images.githubusercontent.com/1000543/182417654-58f7b01b-a1cb-4e30-9a51-ad2ea8052927.png)

There is an option in Formidable Forms to not use the Formidable styles.

**Comment by Herm71** [comment]
![formidable-no-style-front-end](https://user-images.githubusercontent.com/1000543/182417826-f69c71ca-3536-4966-b5d2-0695221c983f.png)

It doesn't look very pretty on the front end, though

**Comment by Herm71** [comment]
I think the best bet would be to leave the styles "on" and style what we want with overrides.

**Comment by knice** [comment]
Is there a way to create a "theme" for a form? It seems like you can switch between appearances in form settings. Is it possible to create an appearance that someone can choose for the form?

**Comment by Herm71** [comment]
Upon further digging, it is possible to create a theme for a form.
![formidable-styles](https://user-images.githubusercontent.com/1000543/182939171-91a360b2-58df-4be3-9082-23a25a8a75f8.png)

see also [https://formidableforms.com/knowledgebase/visual-form-styler/](https://formidableforms.com/knowledgebase/visual-form-styler/) 

I have created a new form theme template using this method. I have changed (some) colors and fonts to reflect UCSC branding We are able to save it and export/import it. 
![formidable-detail](https://user-images.githubusercontent.com/1000543/182940245-f136883f-81ac-4077-922e-8d97fcdef61f.png)

I have created a [Kitchen Sink](https://test-jchafin.wordpress-dev.ucsc.edu/kitchen-sink/) page on my test site that roughly matches the fields and options in the style builder. This way the styles for all available fields can be reviewed and adjusted.

**Comment by knice** [comment]
@Herm71 What do you get when you export it? What is in the file?

**Comment by Herm71** [comment]
@knice it's an XML file. One has the option of exporting styles only, but it's still an XML (or CSV) file.
![formidable-export](https://user-images.githubusercontent.com/1000543/182963723-a520b5ea-d2ad-42f0-b662-384cc6967b5c.png)

**Comment by knice** [comment]
Aw, poop. And it looks like it's specific to an individual form?

@Herm71 Looks like the best approach is what we talked about yesterday: duplicate their default stylesheet, change the CSS custom properties to match our theme, and add that sheet to our theme stylesheet.

**Comment by knice** [comment]
We've moved away from Formidable Forms in favor of Gravity Forms
